### ISSUE TITLE
macos docker build failing

### ISSUE THREAD

**Issue by adioanca** [justadudewhohacks/opencv-express#2]
Hi,

I'm new to all nodejs stuff, and I need help with opencv-express demo pls.

I've tried with Node 8.x, then cleaned all up (hard delete) and tried this:

  395  brew reinstall node@6
  396  ls
  397  ######### rm -rf opencv-express/ object-tracking/
  398  npm install --save opencv4nodejs
  399  git clone https://github.com/justadudewhohacks/opencv-express.git
  400  cd opencv-express/
  401  docker-compose build
  402  history

I've put the output in:
[opencv-express docker build fail.log](https://github.com/justadudewhohacks/opencv-express/files/1364710/opencv-express.docker.build.fail.log)

Could you please have a look?

I've searched a bit the internet why it fails, and it appears 'node-gyp' need a file in your repository: binding.gyp
Maybe it's that, maybe it not...

Thanks and looking forward to see some visuals of your work ;)

**Comment by justadudewhohacks** [comment]
Hey,

Thanks for reporting this. This was my fault I accidentally added opencv4nodejs to the package.json, which will fail because I removed all the build tools from the docker image. The provided docker image has opencv4nodejs already installed globally.

You dont have to install node, OpenCV or opencv4nodejs on your local machine to run this. All you need is docker. I pushed a fixed version, simply running docker-compose build and docker-compose up should be enough and you are ready to go.

Sorry for the inconvinience.

**Comment by adioanca** [comment]
Hi,

It worked. I can open localhost:3001.

However nothing happens when I load an image and press "detect face" button. It times out.

(it also complained about a favicon.ico, but I've downloaded one and put it in all folders; then I got into the timeout issue.)

But, that's another issue, for another day. :)

Thanks,
Adi.

**Comment by justadudewhohacks** [comment]
If the request times out, the image is probably pretty big? What size is your image, you could try a down-scaled version. The favicon.ico is just the small icon you see in the tab of your browser, you can ignore the warning.

Do not hesitate to open another issue and attach the image/s, which you have trouble with. ;)
